### ISSUE TITLE
Unsure what fan to use

### ISSUE THREAD

**Issue by stackingdeezlayers** [sneakytreesnake/CrownCooler#1]
I don't even know what fan to use. That should probably be something you specify. Thanks!

**Comment by sneakytreesnake** [comment]
Did you mean the part cooling fan or the hotend fan?

The hotend cooling fan is a 2510 fan.

**Comment by stackingdeezlayers** [comment]
> Did you mean the part cooling fan or the hotend fan?
> 
> The hotend cooling fan is a 2510 fan.

I meant the part cooling fan. Thanks!

**Comment by sneakytreesnake** [comment]
I've updated the readme - let me know if that makes it clearer.

**Comment by stackingdeezlayers** [comment]
Thank you, I appreciate that very much. I'll definitely look into doing this once my trident is done. It looks like an amazing part cooling solution

Also, I see you still are using the normal 2020 extrusion on the X-axis. Maybe consider carbon fiber? Here is great video explaining the whole light X-axis thing: https://youtu.be/Yzr6elGFR44

Edit: Oops, you are using carbon fiber. My bad
