### ISSUE TITLE
New fan option suggest : dual rotor 4056

### ISSUE THREAD

**Issue by ChipCE** [sneakytreesnake/CrownCooler#10]
I'm using 4056 fan on my printers and it gives quite good result. I think the output power will be in the middle between 4028 and CPAP. 
In my setup, I use quite small tube so i need an extra adapter with 5015 fan to reduce the back flow. I think it will work as-it in your design. 
![Screenshot_2023-08-29_10-38-59](https://github.com/sneakytreesnake/CrownCooler/assets/22391265/63a315f4-1217-46b4-95d7-f0b87ce198e5)

https://www.aliexpress.com/item/1005003803489167.html?spm=a2g0o.productlist.main.23.29c5598fqS6UwC&algo_pvid=20b23075-433c-4fee-ac69-6ca7c0f48132&algo_exp_id=20b23075-433c-4fee-ac69-6ca7c0f48132-11&pdp_npi=4%40dis%21JPY%21767%21729.0%21%21%215.14%21%21%40210318b816932732960654868ee1b2%2112000027220420481%21sea%21JP%21862447013%21&curPageLogUid=tc5Xl7uHNrzY

**Comment by sneakytreesnake** [comment]
Hi, thanks for the suggestion.

The focus of this mod is closer to adapting a CPAP tube to a voron style carriage.
While I have included a few different options to attaching to fans (WS7040, 4028), I largely consider further fan support up to the end user (i.e. not this mod).
