### ISSUE TITLE
Can it be made compatible with other extruders?

### ISSUE THREAD

**Issue by Mapte146** [sneakytreesnake/CrownCooler#11]
Hello, I understand it's made specifically for a Voron printer but I really like the design of the crown style cooling duct. I am
wondering if it can be used for my Sprite extruder for my CR 10 smart pro. Is there a way you can modify the design to fit sprite extruder? or if you can upload stp file of the crown portion of your design I can modify it too so it can be used for my sprite extruder. Thank you.

**Comment by sneakytreesnake** [comment]
Hi, thanks for the suggestion. 

It looks like the sprite extruder is significantly different than the Voron Stealthburner style, so I am not sure it will work without a complete re-design.

For now, I want to keep this design focused on the Voron range of extruder/carriage systems.
