### ISSUE TITLE
Is this toolhead compatible with the BTT Ebb Sb2209?

### ISSUE THREAD

**Issue by cray12399** [sneakytreesnake/CrownCooler#13]
Hi, first of all, this toolhead is absolutely impressive and thank you for the hard work in designing it.

I really want to add it to my build, but I am using the BTT Ebb sb2209. Is this toolhead compatible with that board? Or if not, are there plans to make it compatible in the future?

**Comment by cray12399** [comment]
Also, is it compatible with Bowden via the m4?

**Comment by realJosef** [comment]
Hi,
i've nothing to do with this project but use the printhead and love it since.
i think i can give you a clear no for both questions.

The sb2209 is made for Stealthburner and nothing else.

**Comment by cray12399** [comment]
@realJosef thank you for your response. Now that I look into it, the SB2209 mounts to the extruder, and the Mobius M4 toolhead part is based on clockwork 2. So, I think it might actually be workable. Ill see if I can make it work and report my results.

**Comment by realJosef** [comment]
Yes the M4 is based on the CW2 but only the internal design its not meant to be mounted to the toolhead.
I dont think that the work will give you any benefits.

**Comment by cray12399** [comment]
@realJosef Yes, the Mobius has an external extruder mechanism that is mounted away from the toolhead, but there is also a clockwork-style body that mounts to the toolhead and routes the filament to the hotend. It uses the same mounting mechanism as the clockwork so I don't see a reason it shouldn't work. Here's a link to it: https://github.com/VoronDesign/Voron-Stealthburner/tree/main/STLs/Clockwork2/Bowden

**Comment by realJosef** [comment]
Sorry i think i miss understood you. i thought you wanted the m4 ON your toolhead.
This could work for sure. you only need to adapt the frontcover for the can board then.

**Comment by sneakytreesnake** [comment]
@realJosef answered correctly, this mod doesn't directly supported Bowden inputs or have any mounting hardware for the BTT EBB SB2209.

In saying that:
1) this mod maintains combability with the stealthburner system. It uses the standard stealthburner x carriage, and all the mounting hardware is the same. So if you wanted, you could use a stealthburner bowden mod, like [here ](https://www.printables.com/model/139183-ender-3-v2-voron-stealthburner-conversion/files)(though I haven't tested this)

2) There is enough space around the toolhead to make a SB2209 mount... but it will be kinda jank. I use a EBB36 and this mounts well within the whole assembly.
