### ISSUE TITLE
Dragon HF not fitting

### ISSUE THREAD

**Issue by Burtila** [sneakytreesnake/CrownCooler#14]
Hi, try to fit a dragon HF hotend, but is not is not possible.
Do you have some extra component for dragon hf?
![Capture4](https://github.com/sneakytreesnake/CrownCooler/assets/95863605/b9a63e75-cd63-41fd-b7b5-126a89a21632)
![Capture3](https://github.com/sneakytreesnake/CrownCooler/assets/95863605/9213efc6-0f8d-49ac-bf64-192a79bed3ee)
![Capture2](https://github.com/sneakytreesnake/CrownCooler/assets/95863605/17f996ac-24ae-4bae-9784-10c9ce82d51d)
![Capture1](https://github.com/sneakytreesnake/CrownCooler/assets/95863605/0d5f085f-7bc9-4745-b57d-c8f7a98fa63a)

**Comment by sneakytreesnake** [comment]
Noted, it doesn't fit. Will need to update.

I will have to release a new duct to be compatible with dragon HF/Rapido HF for it to be compatible. Will close this issue once I've made that update.

**Comment by zerosnugget** [comment]
Are you already working on that update? I also use a Dragon HF and would like to use the newer version of this mod.

**Comment by Burtila** [comment]
Hi, i don`t what to be pushy, but the update will be available soon?

**Comment by sneakytreesnake** [comment]
I'm aiming to have a dragon HF version ready sometime in July.
Fitting the duct in with a much shorted hotend is proving to be somewhat of a challenge though.

**Comment by Burtila** [comment]
Any update?

**Comment by sneakytreesnake** [comment]
I have uploaded dragon toolhead STLs [here ](https://github.com/sneakytreesnake/CrownCooler/tree/main/STL/Toolhead).

However, if you are using the standard X carriage you will have fitment problems with the duct (the metal ones are fine). Ill update this soon.

**Comment by sneakytreesnake** [comment]
Added X carriage
