### ISSUE TITLE
Financially supporting your projects

### ISSUE THREAD

**Issue by zerosnugget** [sneakytreesnake/CrownCooler#15]
This is more of a general question, but I'm mostly interested in the crowncooler mod so that's why I'm opening the issue here. I would like to ask, if there is any way to support you financially to most importantly help you working on your projects and maybe also speed things up a little. I didn't see any option to be a GitHub Sponsor so that's why I'm asking.

Thank you for your effort so far!

**Comment by sneakytreesnake** [comment]
Hello,

I'm running behind on developing most of these projects lately due to having to pick up an extra job... so this may not be a bad idea.

I haven't heard about Github Sponsors before, so I've set up an account now. I am sure it will appear on my account soon.

In terms of actually making some progress on this project, are you able to contact me on discord to describe your setup (hotend, probes, etc)?

**Comment by zerosnugget** [comment]
Hey,
thx for the quick response and sorry for taking so long to answer. I don't know if you've got any response from Github yet but there is still no sponsor button on your profile. Maybe this really would help you if you've financial issues. I hope it gets unlocked soon and a couple of people consider supporting you! I can, but I still want to state here that I'm using the Dragon HF in combination with the Orbiter V2 extruder and a Beacon.
For the X carriage to support the Beacon sensor I've been using this 180° degree version: [https://www.teamfdm.com/files/file/686-beacon-cw2-stealthburner-alternative-mounts/?tab=reviews&sort=newest#review-84](https://www.teamfdm.com/files/file/686-beacon-cw2-stealthburner-alternative-mounts/?tab=reviews&sort=newest#review-84)

I've recently printed the "legacy" Parts for my build because the Dragon Hotend is still missing in the new version. So far it's working great except the 2510 Fan blowing against the Hotend Cooler worries me a bit (there aren't many options as far as I could find especially for 24v and it seems pretty weak)

**Comment by sneakytreesnake** [comment]
No worries. 

I'm working on a new release, aiming for July. I'll do my best to include support for the beacon sensors and dragon HF hotends.

I'll see if I can get the sponsor system to work, but I want to make it clear that I have no expectations for support :-)

**Comment by zerosnugget** [comment]
I'm looking forward to that! Like I said the 180 Degree Version works perfectly (it justs offsets the mount further to the back. I can attach a picture later to this thread.

Yeah of course that's totally reasonable!

**Comment by Korolen** [comment]
@sneakytreesnake I looked at both the repo page and your user page, and I still don't see the option to sponsor? I'd love to chip in as well to help the project along and show appreciation.

**Comment by sneakytreesnake** [comment]
Hi @Korolen . Firstly, thank you for your support!

Unfortunately, I am still waiting for Github themselves to review my profile. I'm submitting a support ticket to see if that makes some progress...

In any case, I'll update this thread once it has gone through :-)

**Comment by sneakytreesnake** [comment]
Hi all,

Support has come back and approved my github sponsors account :-)
