### ISSUE TITLE
Tap Support

### ISSUE THREAD

**Issue by S1L3NTANG3L** [sneakytreesnake/CrownCooler#16]
Not an issue but a question XD, Want to run this with tap and was wondering if you have though of an version that'll work?

**Comment by sneakytreesnake** [comment]
Hello,

I haven't checked if it's compatible with TAP yet.

Could you give me an idea of your setup so I can check? What hotend, probe, etc are you using?

**Comment by S1L3NTANG3L** [comment]
I'm busy building a Trident but I had a bit of a think and the tap is the better option in terms of rigidity, great design btw!
