### ISSUE TITLE
New beta duct may interfere with carriage

### ISSUE THREAD

**Issue by woodencliff** [sneakytreesnake/CrownCooler#18]
[crown mount on xol carriage.zip](https://github.com/user-attachments/files/16707495/crown.mount.on.xol.carriage.zip)
Looking foward to your design! I'm planning to migrate from xol toolhead to CrownCooler. I imported the new beta duct into cad and tried to assemble, found that the rear part is colliding with the bottom of carriage. I'm using xol carriage(https://github.com/Armchair-Heavy-Industries/Xol-Toolhead/blob/main/STL/Xol-Carriage/Xol-Carriage_MGN12H.stl) ,and the stock cw2 carriage has a even larger chin, which may cause a even bigger problem.

**Comment by sneakytreesnake** [comment]
Updating the carriage will be in the next update.

Alternatively, the "cartographer metal bracket" x carriages are already compatible.

**Comment by sneakytreesnake** [comment]
I've added a trimmed down X carriage.
