### ISSUE TITLE
Collision with front doors

### ISSUE THREAD

**Issue by madnezzm** [sneakytreesnake/CrownCooler#3]
Voron 2.4 300mm. Rapido hotend
The air duct is in contact with the front doors. Fan goes further.
Need a more compact size by 12-15mm on the Y axis, not including the fan
![IMG_0371](https://user-images.githubusercontent.com/17692546/227812457-72a89f60-5d21-4017-9c6e-c8384b2fae1e.jpeg)
![IMG_0372](https://user-images.githubusercontent.com/17692546/227812470-f67c2360-cbc3-42f8-9218-6875a6232a03.jpeg)

**Comment by sneakytreesnake** [comment]
You are correct in that the duct will hit the front panel when moving the toolhead to Y=0. I do intend to fix this in the near future once the more pressing issues have been resolved.

Is there a particular reason that you are mounting the fan directly on the toolhead? One of the main benefits of the CPAP designs is to take the weight of the high powered fans off the toolhead. It was intended that the fan, in your case the 4028 fan, is mounted either to the gantry or outside the enclosure.

**Comment by madnezzm** [comment]
I installed a fan on my toolhead because the CPAP pipe and the turbine are on delivery.  For me, collision with doors is the main problem that prevents me from using this solution.  I'm really looking forward to the fix.  Can you add cad files?  Then I can correct and submit a PR.

**Comment by sneakytreesnake** [comment]
I am still actively developing (including moving the duct in so it doesn't hit the doors) so I won't release the CAD just yet.

Once the designs are a bit more finalised, I will release the CAD.
