### ISSUE TITLE
V2 cooler w/Orbiter Filament Sensor

### ISSUE THREAD

**Issue by ndng28** [sneakytreesnake/CrownCooler#4]
Any plans to add extruder motor cooling compatibility with Orbiter v2 Filament sensor?

**Comment by sneakytreesnake** [comment]
Have you considered using the [Turbiter](https://www.orbiterprojects.com/turbiter/)? It is made by the same developer as the orbiter & orbiter sensor.

**Comment by ndng28** [comment]
Thanks for the link. I was not aware of the turbiter project but it won't fit my use case since I am using a EBB36 board.

**Comment by sneakytreesnake** [comment]
To answer the original question, I don't plan on making another extruder cooler that is compatible with canbus boards and the orbiter sensor at the same time.

**Comment by ndng28** [comment]
No worries. Thanks
