### ISSUE TITLE
V2 When?

### ISSUE THREAD

**Issue by BlackShadeOSS** [sneakytreesnake/CrownCooler#5]
I was wondering when the v2 will come out, because I realy like the design but v2 looks like its more compact.

**Comment by BlackShadeOSS** [comment]
I also would be happy to test it.

**Comment by sneakytreesnake** [comment]
Hi, the V2 is already out, just check the STL files.

FYI, the V2 only supports the rapido UHF hotend for now. I'll add some more in the future.

**Comment by BlackShadeOSS** [comment]
oh I need dragon hf version

**Comment by sneakytreesnake** [comment]
Understand, Ill make a dragon HF version next.

**Comment by BlackShadeOSS** [comment]
thanks for your awesome work

**Comment by BlackShadeOSS** [comment]
Any update on dragon hf version ?

**Comment by BlackShadeOSS** [comment]
@sneakytreesnake any updates?

**Comment by sneakytreesnake** [comment]
A dragon HF version has been added
