### ISSUE TITLE
WS7040 Wiring and configuration

### ISSUE THREAD

**Issue by Maceon12** [sneakytreesnake/CrownCooler#9]
I am attempting to set up a ws7040 on my voron trident using a v1.1 octopus board and have found that the fan is turning on at max speed as soon as the printer turns on. This appears to be because the octopus drives the pwm on the ground pin, instead of the 5v pin. Because of this the fan has to be driven off the raspberry pi which is not intuitive for most users. Can a guide on the wiring be added to the instructions. Alternatively, the yotube channel Vez3D has an excellent tutorial on the cpap remote cooling setup (https://youtu.be/E3kBau82SwU) so a link to his video would also be useful, either in place of or alongside wiring and config instructions.

**Comment by Ekodas** [comment]
I haven't wired mine up just yet, but I believe the work around for this is to actually use one of the Octopus boards endstop pins instead of a fan header pin.

**Comment by realJosef** [comment]
just finished my Installation yesterday.

this link will show you how to setup the pwm fan. i used 24V+ from the PSU and a heater - for the GND wire. PWM is on a FAN-
https://os.ratrig.com/docs/guides/4028/

**Comment by sneakytreesnake** [comment]
answered by @realJosef
